### ISSUE TITLE
Improve the working of draggable Input Box

### ISSUE THREAD

**Issue by itsrishibajpai** [devclub-biet-jhansi/visualising-stack-implementation#1]
There is a draggable Input box beside Stack in the main box, which can be dragged all over the screen to take user Input as ` Push ` or ` Pop ` function in the stack. This however doesn't fits well with the design and overlays sometimes with some components. 
This should be made more appropriate.
Feel free to comment your suggestions.

**Comment by iamrishirb** [comment]
Hey there, 

I saw the functioning of draggable div Box that takes input. there might be some opacity issues or something else which needs to be fixed to prevent it from creating an overlapping effect. 
I would like to work on this issue.

**Comment by build-with-rishi** [comment]
> Hey there,
> 
> I saw the functioning of draggable div Box that takes input. there might be some opacity issues or something else which needs to be fixed to prevent it from creating an overlapping effect.
> I would like to work on this issue.

**Comment by build-with-rishi** [comment]
Hi there,

I have done some work to make it look more adaptable with the design. Please check it and tell me if anything else needs to be done.
