### ISSUE TITLE
Include some kind of Questionnaire / Quiz to check student's knowledge

### ISSUE THREAD

**Issue by itsrishibajpai** [devclub-biet-jhansi/visualising-stack-implementation#3]
Student will perform some operation on Stack with the help of options available in the Simulator. there should be any option like a quiz which can be used to check their knowledge level after performing these operations that whether they grasped the content or not?

**Comment by avinash-chandravansi** [comment]
Hi ,

I can make a popup question box using css and JavaScript.

**Comment by iamrishirb** [comment]
Hello @avinash-chandravansi,

Would you mind if I also try designing some kind of popup? I am good in CSS let's create something together

**Comment by build-with-rishi** [comment]
> Hi ,
> 
> I can make a popup question box using css and JavaScript.

Hello @avinash-chandravansi,

Would you mind if I also try designing some kind of popup? I am good in CSS let's create something together

**Comment by build-with-rishi** [comment]
I have tried to design a quiz box. Please do give it a review
